# Workflow to auto fail
# Easy way to get a guaranteed notification to test with

name: Force Fail
on:
  workflow_dispatch:

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: This will fail on purpose
        run: exit 1
